### ISSUE TITLE
Class sortation broken

### ISSUE THREAD

**Issue by jblacksberg** [Pattern-Labs/django-bom#3]
The classes are sorted alphabetically not numerically. This means that when I added a 4th digit to the PN classes, Django lost its mind and started shooting. Only you! can save the day, help (: ?

**Comment by Travis-Taylor** [comment]
After chatting in person, it sounds like you've moved past this issue by adding the 4th digit to the existing PNs. I'll close this request unless we get into the habit of spinning up new indaBOM instances and having to mess with the class structure regularly
