### ISSUE TITLE
IndaBOM Improvement Laundry List

### ISSUE THREAD

**Issue by mfedick** [Pattern-Labs/django-bom#6]
**Timing:** Ideal to have these updates made before the H001 BOM is released. 

1. Removing the leveling system 
- [ ] Anything that is listed as a sub-assy level is removed [mainly 2s and 3s I think], with only its included components kept. Ex - Amcrest camera sub-assy has three sub-assy per robot. A specific cable is 1 per sub-assy. The sub-assy line of 3 is removed. The component level is increased from 1 to 3. 
- [ ] Add a new column for sub-assy. Beneficial because [1] this is the new way to see which sub-assy each component is a part of and [2] gives the ability to see if the same part is used in multiple sub-assemblies. 

2. Adjust the lead time to weeks instead of days. Rounding up. ex - 10 days = 2 weeks, 14 days = 2 weeks, 15 days = 3 weeks.

**Comment by Travis-Taylor** [comment]
https://github.com/Pattern-Labs/django-bom/pull/7

**Comment by Travis-Taylor** [comment]
Fixed in https://github.com/Pattern-Labs/django-bom/pull/8

FYI the `extended_qty` field is the correct total value, you can ignore the `quantity` field as it's just per-subassembly. And you will have to use the "Flat" export (not the "Indented" export) to get the correct values

**Comment by Travis-Taylor** [comment]
@mfedick I deployed the changes here to indaBOM, on Monday let's get a test export CSV and check that you're happy
